### ISSUE TITLE
Not Able to include in android studio Mac 

### ISSUE THREAD

**Issue by vikrams061** [mkoslacz/MoviperTemplateGenerator#25]
Hello I am trying to use MoviperTemplateGenerator in android studio with mac osx but i am not able to make this heppen as in mac i don't find any plugin folder with android studio again i tried with android studio preferences but nothing works got error on http clone so if you can help me with the instructions for mac .

**Comment by vikrams061** [comment]
finally worked but you must add installation for mac systems -> path for templates is 

/Applications/Android Studio.app/Contents/plugins/android/lib/templates/other/ ---->Mac Only 

Thanks

**Comment by mkoslacz** [comment]
That's correct. I've already added it. Thanks a lot. I sincerely apologize for replying late to your issue.
